# Write your MySQL query statement below
SELECT ACTIVITY_DATE AS DAY ,COUNT(DISTINCT USER_ID) AS ACTIVE_USERS FROM
ACTIVITY 
WHERE DATEDIFF('2019-07-27', activity_date) < 30
    AND DATEDIFF('2019-07-27', activity_date) >= 0
GROUP BY ACTIVITY_DATE